### PR TITLE
Fix new genios UI

### LINKED ISSUE #320: Umstellung der Genios-Webseite: Bibbot funktioniert nicht mehr
Genios hat seine Seite (zumindest für meine Bibliothek) neugestaltet. Bibbot funktioniert nun nicht mehr.

### PR DESCRIPTION
**Pull request by Travior**
This would fix #320 
The new login page requires an input event, otherwise the login credentials will be discarded on submit

### CODE REVIEW

**Comment by Travior** [comment]
I'm currently checking whether the bookmark icon is available as a method of checking whether the user is already logged in to genios. Not sure if this is the most elegant way, it works for now but I'm open for suggestions

**Comment by stefanw** [comment]
There are libraries that use the old interface, so we can't just replace the genios provider. Please create a new provider named `new.genios.de` (it's just a name). Then we can set a `defaultSource` on the affected providers to use that source.

**Comment by Travior** [comment]
I have changed my initial code to have the genios source configurable with an optional `defaultSource `in the provider Object.
From my testing this should now only switch to the new.genios.de source for explicitly marked providers, I could however only test this with my library in Essen

**Comment by Travior** [comment]
It seems that (at least for my library) the old search link now redirects to the new genios UI (at least I get a 302 back).
I'll try to change the search and scrape logic for the new UI as well

**Comment by traubenzuckerberg** [comment]
Ist das Problem jetzt behoben?

**Comment by merula75** [comment]
@Travior thanks for this fix. I checked the list of providers and these 
```
bib-darmstadt.genios.de 
bib-halle.genios.de 
bib-jena.genios.de 
sbdresden.genios.de 
bib-oberhausen.genios.de 
bib-oranienburg.genios.de 
bib-luedenscheid.genios.de
bib-bayern.genios.de
```
use the same new login page. Could you add
```
    defaultSource: 'new.genios.de'
```
to them as well?

**Comment by mangerlahn** [comment]
Not too familiar with this, but may also apply to Leipzig:

'''
stadtbib-leipzig.genios.de
'''

**Pull request merged**
